# Generated by Django 4.2.1 on 2023-07-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweets',
            old_name='Text',
            new_name='text',
        ),
    ]
