# Generated by Django 4.2.1 on 2023-07-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
