# Generated by Django 4.2.1 on 2023-07-19 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0006_recommendation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendation',
            new_name='SVDRecommendations',
        ),
    ]
