# Generated by Django 4.2.1 on 2023-07-19 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0007_rename_recommendation_svdrecommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svdrecommendations',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svd_recommendations', to='data.tweets'),
        ),
        migrations.AlterField(
            model_name='svdrecommendations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svd_recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TFRSRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfrs_recommendations', to='data.tweets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfrs_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KNNRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knn_recommendations', to='data.tweets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knn_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HybridRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_recommendations', to='data.tweets')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
