# Generated by Django 4.2.1 on 2023-07-19 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_svdrecommendations_tweet_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchData',
        ),
    ]
