# Generated by Django 4.2.1 on 2023-07-21 10:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_delete_searchdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='entities',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='key_phrases',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='sentiment_scores',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
